name: Deploy Infrastructure to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: aguadamillas_students_1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
          resourceGroupName: BCSAI2024-DEVOPS-STUDENTS-A-UAT
          template: ./infra/main.bicep
          parameters: ./infra/main.parameters.json 
